application: <project-id>
version: test
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /api/sync
  script: src.main.APP
  secure: always
  login: admin

- url: /api/run
  script: src.main.APP
  secure: always
  login: admin

- url: /api/.*
  script: src.main.APP
  login: required
  secure: always
